version: ~> 1.0

os: linux
dist: bionic

branches:
  only:
    - master
    - release

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile

before_script:
  - cp .env.example .env

script:
  - yarn test

before_deploy:
  - yarn prod

deploy:
  - provider: s3
    edge: true
    detect_encoding: true
    dot_match: true
    local_dir: .build/production/web
    cache_control:
      - 'public, max-age=31536000: *'
    region: $AWS_DEFAULT_REGION
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_S3_BUCKET
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(master|release)$

after_deploy:
  - pip install --user awscli
  - aws s3 cp s3://$AWS_S3_BUCKET/index.html s3://$AWS_S3_BUCKET/index.html --metadata-directive REPLACE --cache-control no-cache
  - aws s3 cp s3://$AWS_S3_BUCKET/index.html.gz s3://$AWS_S3_BUCKET/index.html.gz --metadata-directive REPLACE --cache-control no-cache
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "*"
